### ISSUE TITLE
Your Discord bot token is public.

### ISSUE THREAD

**Issue by Hatsuney** [voctorbidoof/vocsbot#3]

**Comment by DimDown** [comment]
Yep, we haven't pushed the new release yet, and that token is out of date.

**Comment by Hatsuney** [comment]
i don't know about now, but it worked when i wrote this

**Comment by voctorbidoof** [comment]
New tokens have been created

**Comment by Hatsuney** [comment]
yes, you have created new tokens and **commited them too.**

**Comment by DimDown** [comment]
Final solution, we've stopped being _complete_ idiots and put them into files, with a .gitignores on them. No additional dependencies for readline, I hope.

**Comment by Hatsuney** [comment]
yay!
